In [1]:
import pandas as pd

In [2]:
latest_ods = pd.read_csv("../../pipeline/pipeline_steps/input_files/2012-01-2025-03-overdoses.csv")

/tmp/ipykernel_536105/4034167975.py:1: DtypeWarning: Columns (11,28,36,46) have mixed types. Specify dtype option on import or set low_memory=False.
  latest_ods = pd.read_csv("../../pipeline/pipeline_steps/input_files/2012-01-2025-03-overdoses.csv")

In [ ]:
older_ods = pd.read_csv("../../pipeline/pipeline_steps/input_files/2012-01-2025-01-overdoses_old.csv")

/tmp/ipykernel_536105/3778681592.py:1: DtypeWarning: Columns (13,30,36,46) have mixed types. Specify dtype option on import or set low_memory=False.
  older_ods = pd.read_csv("../../pipeline/pipeline_steps/input_files/2012-01-2025-03-overdoses1211.csv")

In [14]:
latest_ods['DeathDate']  = pd.to_datetime(latest_ods['DeathDate'])

In [15]:
latest_ods[(latest_ods['DeathDate'] > '2023-05-31') & (latest_ods['DeathDate'] < '2023-12-31')]

,CaseNumber,Age,Gender,Race,ResidenceType,DeathPlace,DeathAddress,DeathCity,EventPlace,EventAddress,...,ExperiencingHomelessness,Address,CT20,LABEL,ShapeSTArea,ShapeSTLength,ZIPCODE,Shape_Length,Shape_Area,DateOfBirth
16763,2023-06398,41.0,Male,LATINE,Residence,Residence,464 East 30th Street,Los Angeles,NaN,"464 East 30th Street, Los Angeles, 90011",...,NaN,"464 E 30th St, Los Angeles, California, 90011",226701.0,2267.01,4.048388e+06,9183.652275,90011.0,57120.064671,1.195795e+08,NaN
16764,2023-06410,49.0,Male,WHITE,Residence,Residence,"423 East 7th Street Apt 517, Los Angeles, Cali...",NaN,NaN,"423 East 7th Street Apt 517, Los Angeles, Cali...",...,NaN,"423 E 7th St, Los Angeles, California, 90014",206301.0,2063.01,1.457910e+06,4943.525817,90014.0,14875.295283,7.917526e+06,NaN
16765,2023-06433,41.0,Female,LATINE,Residence,Hospital,1050 Linden Avenue,Long Beach,Residence,"4130 Hathaway Avenue #2, Long Beach, CA 90815",...,NaN,"4130 Hathaway Ave, Long Beach, California, 90815",575001.0,5750.01,1.049678e+07,18231.313592,90815.0,88367.943900,1.949848e+08,NaN
16766,2023-06442,54.0,Female,LATINE,NaN,Vehicle,4532 West 111th Street,Inglewood,Vehicle,4532 West 111th Street,...,1.0,"4532 W 111th St, Inglewood, California, 90304",601700.0,6017.00,8.159874e+06,12647.154306,90304.0,42782.878748,4.593570e+07,NaN
16767,2023-06448,36.0,Male,WHITE,NaN,Hospital,23845 McBean Parkway,Santa Clarita,NaN,"23845 McBean Parkway, Santa Clarita, 91355",...,NaN,"23845 McBean Pkwy, Valencia, California, 91355",920330.0,9203.30,3.491842e+07,23872.638804,91355.0,158179.702511,4.019611e+08,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18012,2024-00071,62.0,Male,WHITE,NaN,Hospital,2051 Marengo Street,Angeles,Sidewalk,560 Maple Avenue Los,...,NaN,"560 Maple Ave, Los Angeles, California, 90013",206301.0,2063.01,1.457910e+06,4943.525817,90013.0,27153.272524,1.866735e+07,NaN
18013,2024-00077,59.0,Male,BLACK,Residence,Hospital,1513 S. Grand Ave,Angeles,NaN,NULL NULL,...,NaN,"1513 S Grand Ave, Los Angeles, California, 90015",224010.0,2240.10,8.938275e+06,13900.825044,90015.0,37381.586486,4.660262e+07,NaN
18025,2024-00175,66.0,Male,ASIAN,NaN,385,N Rockvale Ave Residence Residence 18528 Chase...,Azusa,NaN,NULL NULL NULL Los Angeles,...,NaN,"N Rockvale Ave, Azusa, California, 91702",400605.0,4006.05,5.348615e+07,37045.527301,91702.0,297423.490050,1.640834e+09,NaN
18189,2024-01274,39.0,Male,LATINE,NaN,Hospital,1680 East 120th Street,Angeles,NaN,NULL NULL,...,NaN,"1680 E 120th St, Los Angeles, California, 90059",540700.0,5407.00,1.243242e+07,16223.026110,90059.0,66238.947247,9.313577e+07,NaN
18681,2024-04655,97.0,Male,ASIAN,Residence,Hospital,9449 San Fernando Road NULL Sidewalk 2105 West...,Valley,NaN,NULL NULL NULL Los Angeles Sidewalk 2105 West ...,...,NaN,"2105 W Pico Blvd, Los Angeles, California, 90006",209810.0,2098.10,1.612738e+06,5415.906958,90006.0,37832.454801,5.370366e+07,NaN

In [9]:
older_ods['DeathDate']  = pd.to_datetime(older_ods['DeathDate'])

In [13]:
older_ods[(older_ods['DeathDate'] > '2023-05-31') & (older_ods['DeathDate'] < '2023-12-31')]

,DeathDate,Age,Gender,Race,Mode,DeathPlace,DeathAddress,DeathCity,CauseA,CauseB,...,ExperiencingHomelessness,Address,CT20,LABEL,ShapeSTArea,ShapeSTLength,ZIPCODE,Shape_Length,Shape_Area,DateOfBirth
16731,2023-06-01,41.0,Male,LATINE,NATURAL,Residence,464 East 30th Street,Los Angeles,ALCOHOL USE,NaN,...,NaN,"464 E 30th St, Los Angeles, California, 90011",226701.0,2267.01,4.048388e+06,9183.652275,90011.0,57120.064671,1.195795e+08,NaN
16732,2023-06-01,49.0,Male,WHITE,ACCIDENT,Residence,"423 East 7th Street Apt 517, Los Angeles, Cali...",NaN,"COMBINED EFFECTS OF FENTANYL, COCAINE AND ETHANOL",NaN,...,NaN,"423 E 7th St, Los Angeles, California, 90014",206301.0,2063.01,1.457910e+06,4943.525817,90014.0,14875.295283,7.917526e+06,NaN
16733,2023-06-01,41.0,Female,LATINE,ACCIDENT,Hospital,1050 Linden Avenue,Long Beach,FENTANYL AND OPIATE TOXICITY,NaN,...,NaN,"4130 Hathaway Ave, Long Beach, California, 90815",575001.0,5750.01,1.049678e+07,18231.313592,90815.0,88367.943900,1.949848e+08,NaN
16734,2023-06-01,54.0,Female,LATINE,ACCIDENT,Vehicle,4532 West 111th Street,Inglewood,EFFECTS OF COCAINE,NaN,...,1.0,"4532 W 111th St, Inglewood, California, 90304",601700.0,6017.00,8.159874e+06,12647.154306,90304.0,42782.878748,4.593570e+07,NaN
16735,2023-06-02,36.0,Male,WHITE,ACCIDENT,Hospital,23845 McBean Parkway,Santa Clarita,ANOXIC ENCEPHALOPATHY,EFFECTS OF FENTANYL AND METHAMPHETAMINE,...,NaN,"23845 McBean Pkwy, Valencia, California, 91355",920330.0,9203.30,3.491842e+07,23872.638804,91355.0,158179.702511,4.019611e+08,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17980,2023-12-30,62.0,Male,WHITE,ACCIDENT,Hospital,2051 Marengo Street,Angeles,HYPOXIC BRAIN INJURY EFFECTS OF COCAINE AND ET...,NaN,...,NaN,"560 Maple Ave, Los Angeles, California, 90013",206301.0,2063.01,1.457910e+06,4943.525817,90013.0,27153.272524,1.866735e+07,NaN
17981,2023-12-07,59.0,Male,BLACK,ACCIDENT,Hospital,1513 S. Grand Ave,Angeles,SEQUELAE OF METHAMPHETAMINE AND PHENCYCLIDINE USE,NaN,...,NaN,"1513 S Grand Ave, Los Angeles, California, 90015",224010.0,2240.10,8.938275e+06,13900.825044,90015.0,37381.586486,4.660262e+07,NaN
17992,2023-12-19,66.0,Male,ASIAN,NATURAL,385,N Rockvale Ave Residence Residence 18528 Chase...,Azusa,ACUTE CARDIAC DYSFUNCTION ATHEROSCLEROTIC CARD...,NaN,...,NaN,"N Rockvale Ave, Azusa, California, 91702",400605.0,4006.05,5.348615e+07,37045.527301,91702.0,297423.490050,1.640834e+09,NaN
18149,2023-12-30,39.0,Male,LATINE,NATURAL,Hospital,1680 East 120th Street,Angeles,SEQUELAE OF CHRONIC DRUG AND ETHANOL USE,NaN,...,NaN,"1680 East 120Th Street, Los Angeles, Californi...",540700.0,5407.00,1.243242e+07,16223.026110,90059.0,66238.947247,9.313577e+07,NaN
18656,2023-12-26,97.0,Male,ASIAN,NATURAL,Hospital,9449 San Fernando Road NULL Sidewalk 2105 West...,Valley,CHRONIC RESPIRATORY FAILURE PNEUMONIA EFFECTS ...,NaN,...,NaN,"2105 West Pico Boulevard, Los Angeles, Califor...",209810.0,2098.10,1.612738e+06,5415.906958,90006.0,37832.454801,5.370366e+07,NaN

In [8]:
latest_ods['Race'].value_counts(dropna=False)

Race
WHITE               8765
LATINE              7718
BLACK               3756
ASIAN                656
NaN                  262
MIDDLE EASTERN       225
AMERICAN INDIAN       57
PACIFIC ISLANDER      45
UNKNOWN               38
Name: count, dtype: int64

In [4]:
import numpy as np

In [5]:
latest_ods['Race'] = latest_ods['Race'].replace({"middleeasternornorthafrican": "MIDDLE EASTERN", "cardiovasculardiseasenull": np.nan, "ck": np.nan, "k": np.nan})

In [7]:
latest_ods.to_csv("../../pipeline/pipeline_steps/input_files/2012-01-2025-03-overdoses-cleaned-1219.csv")

In [ ]:
old_latest.columns

In [ ]:
KEYS = ["CaseNumber"]

In [ ]:
removed = (
    old_latest
    .merge(
        latest_ods[KEYS],
        on=KEYS,
        how="left",
        indicator=True
    )
    .query('_merge == "left_only"')
    .drop(columns="_merge")
)

print(len(removed))

In [ ]:
removed['CaseNumber']

In [ ]:
removed

In [ ]:
cases_24_new[cases_24_new['CaseNum'] == '2024-00046']['InjuryDesc']

In [ ]:
cases_24[cases_24['CaseNum'] == '2024-00046']['InjuryDesc']

In [ ]:
cases_24['InjuryDesc']